Repository HalLengWang/HLW, pull requests merged in 2024-10, with the labels that each got.

#46 todo_list_detail , login_after 수정
  src/main/java/com/todorank/hlw/domain/home/MainController.java
  src/main/java/com/todorank/hlw/domain/user/controller/UserController.java
  src/main/resources/static/styles.login_after.css
  src/main/resources/static/styles.todo_list_detail.css
  src/main/resources/templates/login_after.html
  src/main/resources/templates/todo_list_detail.html
Labels: fix

#53 Update 이슈-템플릿.md
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
Labels: documentation

#54 Feature/lss
  e main
  src/main/java/com/todorank/hlw/domain/remembrance/entity/Remembrance.java
  src/main/java/com/todorank/hlw/domain/remembrance_comment/entity/RemembranceComment.java
  src/main/java/com/todorank/hlw/domain/score/entity/Score.java
  src/main/java/com/todorank/hlw/domain/todo_card/controller/TodoCardController.java
  src/main/java/com/todorank/hlw/domain/todo_card/entity/TodoCard.java
  src/main/java/com/todorank/hlw/domain/todo_card/form/TodoCardForm.java
  src/main/java/com/todorank/hlw/domain/todo_card/repository/TodoCardRepository.java
  src/main/java/com/todorank/hlw/domain/todo_card/service/TodoCardService.java
  src/main/java/com/todorank/hlw/domain/todo_list/DTO/TodoListDTO.java
  src/main/java/com/todorank/hlw/domain/todo_list/controller/TodoListController.java
  src/main/java/com/todorank/hlw/domain/todo_list/entity/TodoList.java
  src/main/java/com/todorank/hlw/domain/todo_list/service/TodoListService.java
  src/main/java/com/todorank/hlw/domain/todo_type_list/entity/TodoTypeList.java
  src/main/java/com/todorank/hlw/domain/todo_type_list/repository/TodoTypeListRepository.java
  src/main/java/com/todorank/hlw/domain/todo_type_list/service/TodoTypeListService.java
  src/main/java/com/todorank/hlw/domain/user/entity/SiteUser.java
  src/main/java/com/todorank/hlw/global/jpa/BaseEntity.java
  src/main/resources/templates/login_after.html
  src/main/resources/templates/todo_card_read_create_page.html
  src/main/resources/templates/todo_list.html
  src/main/resources/templates/todo_list_detail.html
Labels: enhancement

#57 Feature/todo card show
  src/main/java/com/todorank/hlw/domain/todo_card/repository/TodoCardRepository.java
  src/main/java/com/todorank/hlw/domain/todo_card/service/TodoCardService.java
  src/main/java/com/todorank/hlw/domain/todo_list/controller/TodoListController.java
  src/main/resources/templates/todo_list_detail.html
Labels: enhancement

#66 todo_list_detail 페이지 수정
  src/main/java/com/todorank/hlw/domain/user/controller/UserController.java
  src/main/resources/static/rankings_list_page.css
  src/main/resources/static/remembrance.css
  src/main/resources/static/retrospective_from_page.css
  src/main/resources/static/styles.login_after.css
  src/main/resources/static/styles.login_before.css
  src/main/resources/static/styles.todo_list.css
  src/main/resources/static/styles.todo_list_detail.css
  src/main/resources/templates/login_before.html
  src/main/resources/templates/remembrance_page.html
  src/main/resources/templates/retrospective_from_page.html
  src/main/resources/templates/todo_list.html
  src/main/resources/templates/todo_list_detail.html
Labels: fix

#70 Feature/todo card show
  src/main/java/com/todorank/hlw/domain/todo_card/controller/TodoCardController.java
  src/main/java/com/todorank/hlw/domain/todo_card/form/TodoCardForm.java
  src/main/java/com/todorank/hlw/domain/todo_card/service/TodoCardService.java
  src/main/resources/templates/todo_card_read_create_page.html
  src/main/resources/templates/todo_list_detail.html
Labels: enhancement

#72 Feature/todo list detail style modify
  src/main/resources/static/styles.todo_list_detail.css
  src/main/resources/templates/todo_list_detail.html
Labels: fix

#76 Feature/card mod del
  src/main/java/com/todorank/hlw/domain/todo_card/controller/TodoCardController.java
  src/main/java/com/todorank/hlw/domain/todo_card/service/TodoCardService.java
  src/main/resources/static/todo_card_read_create.css
  src/main/resources/templates/todo_card_read_create_page.html
Labels: enhancement

#74 Update issue templates
  .github/ISSUE_TEMPLATE/custom.md
Labels: documentation

#78 Update issue templates
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/트러블-슈팅-템플릿.md
Labels: documentation

#81 Feature/todo list create
  src/main/java/com/todorank/hlw/domain/todo_list/controller/TodoListController.java
  src/main/java/com/todorank/hlw/domain/todo_list/service/TodoListService.java
  src/main/resources/templates/todo_list.html
  src/main/resources/templates/todo_list_detail.html
Labels: enhancement

#86 Feature/remembrance show
  src/main/java/com/todorank/hlw/domain/remembrance/controller/RemembranceController.java
  src/main/java/com/todorank/hlw/domain/remembrance/entity/Remembrance.java
  src/main/java/com/todorank/hlw/domain/remembrance/form/RemembranceForm.java
  src/main/java/com/todorank/hlw/domain/remembrance/repository/RemembranceRepository.java
  src/main/java/com/todorank/hlw/domain/remembrance/service/RemembranceService.java
  src/main/java/com/todorank/hlw/domain/todo_card/controller/TodoCardController.java
  src/main/java/com/todorank/hlw/domain/todo_list/controller/TodoListController.java
  src/main/java/com/todorank/hlw/domain/user/controller/UserController.java
  src/main/resources/static/styles.todo_list_detail.css
  src/main/resources/templates/signup_page.html
  src/main/resources/templates/todo_card_read_create_page.html
  src/main/resources/templates/todo_list_detail.html
Labels: enhancement

#90 Feature/remembrance comment
  src/main/java/com/todorank/hlw/domain/remembrance_comment/controller/RemembranceCommentController.java
  src/main/java/com/todorank/hlw/domain/remembrance_comment/repository/RemembranceCommentRepository.java
  src/main/java/com/todorank/hlw/domain/remembrance_comment/service/RemembranceCommentService.java
  src/main/java/com/todorank/hlw/domain/todo_card/controller/TodoCardController.java
  src/main/java/com/todorank/hlw/domain/todo_list/controller/TodoListController.java
  src/main/resources/static/styles.todo_list_detail.css
  src/main/resources/templates/todo_list_detail.html
Labels: enhancement

#92 Hotfix
  src/main/java/com/todorank/hlw/domain/todo_list/controller/TodoListController.java
Labels: bug

#93 Feature/comment delete
  src/main/java/com/todorank/hlw/domain/remembrance_comment/controller/RemembranceCommentController.java
  src/main/java/com/todorank/hlw/domain/remembrance_comment/service/RemembranceCommentService.java
  src/main/resources/static/styles.todo_list_detail.css
  src/main/resources/templates/todo_list_detail.html
Labels: enhancement

#94 Feature/score
  src/main/java/com/todorank/hlw/domain/score/repository/ScoreRepository.java
  src/main/java/com/todorank/hlw/domain/score/service/ScoreService.java
  src/main/java/com/todorank/hlw/domain/todo_card/controller/TodoCardController.java
  src/main/java/com/todorank/hlw/domain/todo_card/service/TodoCardService.java
Labels: enhancement

#95 Hotfix/score
  src/main/java/com/todorank/hlw/domain/score/service/ScoreService.java
  src/main/java/com/todorank/hlw/domain/todo_card/controller/TodoCardController.java
Labels: bug

#121 Create README.md
  README.md
Labels: documentation
